Normalization Problem

In [1]:
import numpy as np

In [4]:
#This creates the random 5X5 array "X"
X = np.random.random((5,5))
#This displays the array
print("Array X:")
print(X)

Array X:
[[0.8522561  0.97737028 0.73859814 0.77789661 0.77219832]
 [0.814912   0.07064906 0.16828461 0.42560502 0.64177413]
 [0.11738743 0.46972187 0.03258138 0.00718669 0.03692043]
 [0.38855576 0.59069388 0.46139666 0.76790514 0.79295697]
 [0.36466525 0.40532393 0.72410153 0.75280497 0.08782575]]


In [14]:
#This normalizes the array
X_normalized = (X - X.mean()) / X.std()
#This prints the normalized array
print("Normalized X:")
print(X_normalized)

#This saves the normalized array as "X_normalized.npy"
np.save('X_normalized.npy', X_normalized)

Normalized X:
[[ 1.19809404  1.61140975  0.822624    0.95244683  0.9336225 ]
 [ 1.07472748 -1.38395138 -1.06141152 -0.21135137  0.50276509]
 [-1.22955077 -0.065611   -1.50970827 -1.59359983 -1.49537418]
 [-0.33374393  0.33402106 -0.09311339  0.91943992  1.00219884]
 [-0.41266642 -0.27835014  0.77473432  0.8695564  -1.32720804]]


Divisible by 3 Problem

In [16]:
import numpy as np

In [18]:
#This creates an array of the first one hundred positive integers
hundred = np.arange(1,101)

In [19]:
#This squares the numbers and shapes the array into a 10X10 grid
tenbyten = hundred.reshape(10, 10) **2
print("The Array: ")
print(tenbyten)

The Array: 
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [21]:
#This determines all the elements that are divisible by 3
div_by_3 = tenbyten[tenbyten % 3 == 0]
print("The elements divisible by 3: ")
print(div_by_3)

#This saves the array as "div_by_3.npy"
np.save('div_by_3.npy', div_by_3)

The elements divisible by 3: 
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
